### ISSUE TITLE
EMEBSDDI not computing ADP/ not making output files 

### ISSUE THREAD

**Issue by mardilos** [EMsoft-org/EMsoft#114]
While running the EMEBSDDI program the experimental pattern are processed but the ADP is not calculated.

It works with the provided test files, but not with own data sets.

Since we have an Oxford EBSD system we can only use .ebsp files as pattern format (OxfordBinary). Could this be the reason why no output files are calculated/ created?
[EMEBSDDI-run_Si.zip](https://github.com/EMsoft-org/EMsoft/files/4785551/EMEBSDDI-run_Si.zip)
[EMEBSDDI-Si.nml.zip](https://github.com/EMsoft-org/EMsoft/files/4785569/EMEBSDDI-Si.nml.zip)

**Comment by mardilos** [comment]
![EMEBSDDI-fail](https://user-images.githubusercontent.com/65020763/85590312-95792f80-b644-11ea-83ba-321b816d9fcf.png)

Here´s an image of the EMEBSDDI run
after processing the experimental patterns it starts with computing the ADP but immediately stops without an error message or computing the ADP

**Comment by marcdegraef** [comment]
Hi,

this is a known bug that occurs on Windows only, and we are in the 
process of trying to fix it.  The code works just fine on all UNIX 
flavors, including Mac OS X.

Marc.

**Comment by mardilos** [comment]
Hi,
thank you for answering.
Due to this, i started to build EMsoft on my private Macbook. The SDK installation and Package Compilation ran without error messages.
At the moment i still have some problems with the Package Configuration, since ./EMsoftinit is  not working. 
![Bildschirmfoto 2020-06-30 um 00 02 51](https://user-images.githubusercontent.com/65020763/86060499-18dfba00-ba65-11ea-807e-ea3c94e46b74.png)

Can this be due to a wrong compilation?

**Comment by elena-pascal** [comment]
Rather than not working it seems to not exist in the binary folder.

1) Are there any binaries in the folder?
2) Does ls | grep init return anything?
3) Did you skip the Release/Develop folder on purpose?

Elena

**Comment by mardilos** [comment]
Hi Elena,
thank's for the fast answer,
i just did the compilation again and now it works fine. I think there was a problem in the first try with the "make -j" command

**Comment by mardilos** [comment]
The EMsoftint worked but still the same problem when i want to perform the monte carlo simulation...
![Bildschirmfoto 2020-06-30 um 01 33 10](https://user-images.githubusercontent.com/65020763/86066313-1cc60900-ba72-11ea-9a95-351e6e67d36e.png)

**Comment by elena-pascal** [comment]
The program is not found because you did not tell bash the full path to it.
Bash is not looking in all user folders for a program of the name given.You
have two options:

1)  run the commands every-time with the full path of their location.  In
the case above if you do ./EMOpenCL from the Bin directory you would tell
bash look in this directory with ./
2) tell bash to always look in this directory:

% nano ~/.bashrc

This will open a hidden config file that bash will read every time you open
a new terminal
Add at the end:

export PATH="<the full path to EMsoft Bin>/:$PATH"

Where you need to replace everything in <...> with the full path to your
Bin folder

Save and close the file, and open a new terminal. You should now be able to
call EMsoft commands.

**Comment by elena-pascal** [comment]
I'm glad some progress happened.

The program is not found now because you did not tell bash the full path to it.
Bash is not looking in all user folders for a program of the name given.You
have two options:

1)  run the commands every-time with the full path of their location.  In
the case above if you do ./EMMCOpenCL from the Bin directory you would tell
bash to look in this directory with ./
2) tell bash to always look in this directory:
`
% nano ~/.bashrc`

This will open a hidden config file that bash will read every time you open
a new terminal
Add at the end:
`
export PATH="<the full path to EMsoft Bin>/:$PATH"`

Where you need to replace everything in <...> with the full path to your
Bin folder

Save and close the file, and open a new terminal. You should now be able to
call EMsoft commands.
