### ISSUE TITLE
missing kind_map: int - c_int

### ISSUE THREAD

**Issue by TMM-TUDA** [EMsoft-org/EMsoft#145]
All,

When I am using f90wrap, there is an error:
RuntimeError: Unknown combination of type "integer" and kind "c_int" - add to kind map and try again

If I add a line 'c_int': 'int' into the kind_map file, f90wrap runs. 

Is there a better suggestion? 

Thank you!

Hongbin

**Comment by ZacharyVarley** [comment]
This issue can be closed following #167. Additionally, you can find a Docker image (builds for both amd64 and arm64) which has the Python wrappers already built on dockerhub [here](https://hub.docker.com/r/zvarley/emsoft). Building them yourself takes several hours because f2py-f90wrap is single threaded as far as I understand.

**Comment by marcdegraef** [comment]
close #145.
