### ISSUE TITLE
EmsoftWorkbench "Add" element button not working

### ISSUE THREAD

**Issue by clairegriesbach** [EMsoft-org/EMsoft#174]
Hello,

I am trying to use EMSoft (v5.0-Win64) to create master patterns for barium titanate and lead zirconate titanate to use for spherical indexing in EMSphInx. However, the button (+) to add another element and its coordinates does not seem to be working on the "1. Crystal Structure Creation" tab of EMSoft. Is there a workaround to generate the crystal structure file without this?

Thanks for all your work in creating these programs!

Best,
Claire

**Comment by elena-pascal** [comment]
Hello Claire,  

The add element button is [broken in the workbench 5.0](https://github.com/EMsoft-org/EMsoft/issues/109) 

The good news is that it had been fixed in higher versions the bad news is that I think it has never been back-ported. So if you want to use the workbench just have a try with a higher version. Alternatively, the command line option, while a bit more intimidating, it is also a bit more robust ;)

**Comment by clairegriesbach** [comment]
Hi Elena,

Thanks for letting me know! I didn't realize that I downloaded an older verison:)

Best,
Claire
